import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal
from PyQt6.QtWidgets import  QApplication, QWidget
#控制面板窗口
class Ui_Form(QWidget):
    parames_signal = pyqtSignal(str, int)
    def __init__(self):
        super(Ui_Form, self).__init__()
        self.setupUi(self)
        self.reset_all()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(578, 895)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\icon/控制面板.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 581, 901))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color : rgb(55,55,55)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 810, 501, 37))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apply = QtWidgets.QPushButton(parent=self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\icon/确定.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.apply.setIcon(icon1)
        self.apply.setObjectName("apply")
        self.horizontalLayout.addWidget(self.apply)
        self.cancel = QtWidgets.QPushButton(parent=self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\icon/取消.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cancel.setIcon(icon2)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.reset = QtWidgets.QPushButton(parent=self.layoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\icon/重置.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reset.setIcon(icon3)
        self.reset.setObjectName("reset")
        self.horizontalLayout.addWidget(self.reset)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 30, 511, 741))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.control_panel = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.control_panel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_panel.sizePolicy().hasHeightForWidth())
        self.control_panel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.control_panel.setFont(font)
        self.control_panel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.control_panel.setObjectName("control_panel")
        self.verticalLayout.addWidget(self.control_panel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.model_choose = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.model_choose.setFont(font)
        self.model_choose.setObjectName("model_choose")
        self.horizontalLayout_2.addWidget(self.model_choose)
        self.model_set = QtWidgets.QComboBox(parent=self.layoutWidget1)
        self.model_set.setMinimumSize(QtCore.QSize(0, 50))
        self.model_set.setObjectName("model_set")
        self.model_set.addItem("")
        self.model_set.addItem("")
        self.model_set.addItem("")
        self.horizontalLayout_2.addWidget(self.model_set)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.threshold_adjustment = QtWidgets.QLabel(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold_adjustment.sizePolicy().hasHeightForWidth())
        self.threshold_adjustment.setSizePolicy(sizePolicy)
        self.threshold_adjustment.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.threshold_adjustment.setFont(font)
        self.threshold_adjustment.setObjectName("threshold_adjustment")
        self.horizontalLayout_3.addWidget(self.threshold_adjustment)
        self.threshold_set = QtWidgets.QSlider(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold_set.sizePolicy().hasHeightForWidth())
        self.threshold_set.setSizePolicy(sizePolicy)
        self.threshold_set.setMinimumSize(QtCore.QSize(0, 30))
        self.threshold_set.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.threshold_set.setObjectName("threshold_set")
        self.horizontalLayout_3.addWidget(self.threshold_set)
        self.threshold_num = QtWidgets.QSpinBox(parent=self.layoutWidget1)
        self.threshold_num.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold_num.sizePolicy().hasHeightForWidth())
        self.threshold_num.setSizePolicy(sizePolicy)
        self.threshold_num.setMinimumSize(QtCore.QSize(80, 30))
        self.threshold_num.setObjectName("threshold_num")
        self.horizontalLayout_3.addWidget(self.threshold_num)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        #信号与槽函数
        self.threshold_set.valueChanged.connect(self.set_spin_box)
        self.threshold_num.valueChanged.connect(self.set_slider)
        self.apply.clicked.connect(self.send_parames)
        self.cancel.clicked.connect(self.close)
        self.reset.clicked.connect(self.reset_all)

    #获取控制面板设置的参数
    def send_parames(self):
        model_name = self.model_set.currentText()
        threshold = self.threshold_num.value()
        self.parames_signal.emit(model_name,threshold)
        self.close()

    def set_spin_box(self):
        self.threshold_num.setValue(self.threshold_set.value())

    def set_slider(self):
        self.threshold_set.setValue(self.threshold_num.value())
    def reset_all(self):
        self.threshold_set.setValue(50)
        self.model_set.setCurrentIndex(0)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "控制面板"))
        self.apply.setText(_translate("Form", "应用"))
        self.cancel.setText(_translate("Form", "取消"))
        self.reset.setText(_translate("Form", "重置"))
        self.control_panel.setText(_translate("Form", "控制面板"))
        self.model_choose.setText(_translate("Form", "权重选择："))
        self.model_set.setItemText(0, _translate("Form", "NUDT"))
        self.model_set.setItemText(1, _translate("Form", "NUAA"))
        self.model_set.setItemText(2, _translate("Form", "IRSTD"))
        self.threshold_adjustment.setText(_translate("Form", "阈值调节："))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    Ui = Ui_Form()
    screen = app.primaryScreen().availableGeometry()
    window_size = Ui.size()
    x = (screen.width() - window_size.width()) // 2
    y = (screen.height() - window_size.height()) // 2
    Ui.move(x, y)
    Ui.show()
    sys.exit(app.exec())